apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sprayproxy-backend-register
rules:
  - nonResourceURLs:
      - "/backends"
    verbs:
      - get
      - create
      - delete
