# Copyright © 2023 The Spray Proxy Contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sprayproxy-route
  namespace: sprayproxy
  annotations:
    haproxy.router.openshift.io/hsts_header: "max-age=63072000"
spec:
  tls:
    termination: reencrypt 
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: sprayproxy-service
