# Copyright © 2023 The Spray Proxy Contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprayproxy
  namespace: sprayproxy
  labels:
    app.kubernetes.io/name: sprayproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sprayproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sprayproxy
    spec:
      serviceAccountName: sprayproxy
      containers:
        - name: sprayproxy
          image: ko://github.com/redhat-appstudio/sprayproxy
          args:
            - server
          env:
            - name: SPRAYPROXY_SERVER_BACKEND
          ports:
            - containerPort: 8080
              name: server
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: kube-rbac-proxy
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:6000/"
            - "--upstream=http://127.0.0.1:8080/"
            - "--ignore-paths=/proxy,/healthz"
            - "--logtostderr=true"
            - "--v=0"
          ports:
            - containerPort: 8443
              protocol: TCP
              name: https
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sprayproxy-service
  namespace: sprayproxy
spec:
  selector:
    app.kubernetes.io/name: sprayproxy
  ports:
    - name: server
      protocol: TCP
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sprayproxy-api-service
  namespace: sprayproxy
spec:
  selector:
    app.kubernetes.io/name: sprayproxy
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
